name: TaupeGun
version: 2.2.6
author: TheDarven
main: fr.thedarven.main.TaupeGun
commands:
  timer:
    description: Pour changer le chronometre en periode de test.
  revive:
    description: Pour reanimer un joueur.
  heal:
    description: Soigne tous les joueurs.
  g:
    description: Envoie une annonce sur le serveur.
  playerkill:
    description: Supprime un joueur de la partie meme si il est deconnecte.
  players:
    description: Pour voir la liste des joueurs encore en jeu.
  updatestats:
    description: Met a jour la duree de la partie sur le site.
  rules:
    description: Permet de voir les configurations de la partie.
  scenarios:
    description: Permet de configurer la partie.
  taupelist:
    description: Permet aux spectateurs de voir la liste des taupes.
  claim:
    description: Pour avoir son kit de taupe.
  reveal:
    description: Pour se reveler a tous les joueurs en tant que taupe.
  superreveal:
    description: Pour se reveler a tous les joueurs en tant que supertaupe.
  supert:
    description: Pour envoyer un message a son equipe de supertaupes.
  t:
    description: Pour envoyer un message a son equipe de taupes.