name: TaupeGun
version: 2.9.0
author: TheDarven
description: Plugin TaupeGun UHC
main: fr.thedarven.TaupeGun
commands:
  timer:
    description: Pour changer le chronometre en periode de test.
  revive:
    description: Pour reanimer un joueur.
  heal:
    description: Soigne tous les joueurs.
  g:
    description: Envoie une annonce sur le serveur.
  playerkill:
    description: Supprime un joueur de la partie meme si il est deconnecte.
  players:
    description: Pour voir la liste des joueurs encore en jeu.
  rules:
    description: Permet de voir les configurations de la partie.
  scenarios:
    description: Permet de configurer la partie.
    aliases: [config]
  taupelist:
    description: Permet aux spectateurs de voir la liste des taupes.
  claim:
    description: Pour avoir son kit de taupe.
  reveal:
    description: Pour se reveler a tous les joueurs en tant que taupe.
  superreveal:
    description: Pour se reveler a tous les joueurs en tant que supertaupe.
  supert:
    description: Pour envoyer un message a son equipe de supertaupes.
  t:
    description: Pour envoyer un message a son equipe de taupes.
  item:
    description: Pour recuperer les items au lobby.
  say:
    description: Pour envoyer une annonce avec le pseudonyme de l'auteur.
  start:
    description: Pour lancer la partie.
  debug:
    description: Debug pour le developpement.
  coords:
    description: Pour envoyer ses coordonnees a son equipe